// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: some/some.proto

package some

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	SomeRPC(ctx context.Context, in *SomeRequest, opts ...grpc.CallOption) (*SomeResponse, error)
	SomeStreamingRPC(ctx context.Context, opts ...grpc.CallOption) (Service_SomeStreamingRPCClient, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) SomeRPC(ctx context.Context, in *SomeRequest, opts ...grpc.CallOption) (*SomeResponse, error) {
	out := new(SomeResponse)
	err := c.cc.Invoke(ctx, "/some.Service/SomeRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SomeStreamingRPC(ctx context.Context, opts ...grpc.CallOption) (Service_SomeStreamingRPCClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[0], "/some.Service/SomeStreamingRPC", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceSomeStreamingRPCClient{stream}
	return x, nil
}

type Service_SomeStreamingRPCClient interface {
	Send(*SomeRequest) error
	CloseAndRecv() (*SomeResponse, error)
	grpc.ClientStream
}

type serviceSomeStreamingRPCClient struct {
	grpc.ClientStream
}

func (x *serviceSomeStreamingRPCClient) Send(m *SomeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceSomeStreamingRPCClient) CloseAndRecv() (*SomeResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SomeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	SomeRPC(context.Context, *SomeRequest) (*SomeResponse, error)
	SomeStreamingRPC(Service_SomeStreamingRPCServer) error
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) SomeRPC(context.Context, *SomeRequest) (*SomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SomeRPC not implemented")
}
func (UnimplementedServiceServer) SomeStreamingRPC(Service_SomeStreamingRPCServer) error {
	return status.Errorf(codes.Unimplemented, "method SomeStreamingRPC not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_SomeRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SomeRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/some.Service/SomeRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SomeRPC(ctx, req.(*SomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SomeStreamingRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).SomeStreamingRPC(&serviceSomeStreamingRPCServer{stream})
}

type Service_SomeStreamingRPCServer interface {
	SendAndClose(*SomeResponse) error
	Recv() (*SomeRequest, error)
	grpc.ServerStream
}

type serviceSomeStreamingRPCServer struct {
	grpc.ServerStream
}

func (x *serviceSomeStreamingRPCServer) SendAndClose(m *SomeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceSomeStreamingRPCServer) Recv() (*SomeRequest, error) {
	m := new(SomeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "some.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SomeRPC",
			Handler:    _Service_SomeRPC_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SomeStreamingRPC",
			Handler:       _Service_SomeStreamingRPC_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "some/some.proto",
}
