// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: some/some.proto

package some

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SomeRequest) Reset() {
	*x = SomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_some_some_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeRequest) ProtoMessage() {}

func (x *SomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_some_some_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeRequest.ProtoReflect.Descriptor instead.
func (*SomeRequest) Descriptor() ([]byte, []int) {
	return file_some_some_proto_rawDescGZIP(), []int{0}
}

func (x *SomeRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SomeResponse) Reset() {
	*x = SomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_some_some_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeResponse) ProtoMessage() {}

func (x *SomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_some_some_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeResponse.ProtoReflect.Descriptor instead.
func (*SomeResponse) Descriptor() ([]byte, []int) {
	return file_some_some_proto_rawDescGZIP(), []int{1}
}

func (x *SomeResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_some_some_proto protoreflect.FileDescriptor

var file_some_some_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x6f, 0x6d, 0x65, 0x2f, 0x73, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x73, 0x6f, 0x6d, 0x65, 0x22, 0x21, 0x0a, 0x0b, 0x53, 0x6f, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x78,
	0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x53, 0x6f, 0x6d,
	0x65, 0x52, 0x50, 0x43, 0x12, 0x11, 0x2e, 0x73, 0x6f, 0x6d, 0x65, 0x2e, 0x53, 0x6f, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x73, 0x6f, 0x6d, 0x65, 0x2e, 0x53,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x10, 0x53,
	0x6f, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x50, 0x43, 0x12,
	0x11, 0x2e, 0x73, 0x6f, 0x6d, 0x65, 0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x73, 0x6f, 0x6d, 0x65, 0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x73, 0x6f,
	0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_some_some_proto_rawDescOnce sync.Once
	file_some_some_proto_rawDescData = file_some_some_proto_rawDesc
)

func file_some_some_proto_rawDescGZIP() []byte {
	file_some_some_proto_rawDescOnce.Do(func() {
		file_some_some_proto_rawDescData = protoimpl.X.CompressGZIP(file_some_some_proto_rawDescData)
	})
	return file_some_some_proto_rawDescData
}

var file_some_some_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_some_some_proto_goTypes = []interface{}{
	(*SomeRequest)(nil),  // 0: some.SomeRequest
	(*SomeResponse)(nil), // 1: some.SomeResponse
}
var file_some_some_proto_depIdxs = []int32{
	0, // 0: some.Service.SomeRPC:input_type -> some.SomeRequest
	0, // 1: some.Service.SomeStreamingRPC:input_type -> some.SomeRequest
	1, // 2: some.Service.SomeRPC:output_type -> some.SomeResponse
	1, // 3: some.Service.SomeStreamingRPC:output_type -> some.SomeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_some_some_proto_init() }
func file_some_some_proto_init() {
	if File_some_some_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_some_some_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_some_some_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_some_some_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_some_some_proto_goTypes,
		DependencyIndexes: file_some_some_proto_depIdxs,
		MessageInfos:      file_some_some_proto_msgTypes,
	}.Build()
	File_some_some_proto = out.File
	file_some_some_proto_rawDesc = nil
	file_some_some_proto_goTypes = nil
	file_some_some_proto_depIdxs = nil
}
